/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminas;

/**
 *
 * @author Ricardo-Pc
 */
public class Boom extends javax.swing.JFrame {

    /**
     * Creates new form Boom
     */
    public Boom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton41 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ricardo-Pc\\Desktop\\minas.jpg")); // NOI18N
        jLabel3.setText("Tiempo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 32));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, 32));
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, 32));
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 32));
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, 32));
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 32));
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 32));
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 32));
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 32));
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, -1, 32));
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, 32));
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 32));
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, 32));
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, 32));
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, 32));
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 32));
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, 32));
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, 32));
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, 32));
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, 32));
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 32));
        getContentPane().add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, 32));
        getContentPane().add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, 32));
        getContentPane().add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, 32));
        getContentPane().add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, -1, 32));
        getContentPane().add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, -1, 32));
        getContentPane().add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 32));
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, 32));
        getContentPane().add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, 32));
        getContentPane().add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, 32));
        getContentPane().add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, 32));
        getContentPane().add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 32));
        getContentPane().add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 32));
        getContentPane().add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, 32));
        getContentPane().add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, 32));
        getContentPane().add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, 32));
        getContentPane().add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, 32));
        getContentPane().add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, 32));
        getContentPane().add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, -1, 32));
        getContentPane().add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 30));
        getContentPane().add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, 32));
        getContentPane().add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 32));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 79, 50));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 79, 50));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jTextField3.setText("El objetivo del juego es encontrar todas las minas escondidas en el tablero. Para hacerlo se clickea al azar un cuadradito, en donde se vera un numero ese numero indica la cantidad de minas que hay al rededor. Si dice 1 una mina alrededor, 2 dos minas, etc.");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 320, 80));

        jTextField4.setText("Tiempo");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        jTextField5.setText("Bombas restantes");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 100, -1));

        jButton41.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ricardo-Pc\\Desktop\\red-restart-icon-5.png")); // NOI18N
        getContentPane().add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ricardo-Pc\\Desktop\\minas.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
